# Generated by Django 3.0 on 2020-01-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='cname',
            new_name='pname',
        ),
    ]
